#pragma once
#include <ntddk.h>

// Estrutura para retornar a lista de processos suspensos
typedef struct _SUSPENDED_PROCESS_INFO {
    ULONG ProcessId;
    WCHAR ImageName[256]; // Nome da imagem do processo
} SUSPENDED_PROCESS_INFO, * PSUSPENDED_PROCESS_INFO;


// Definindo os novos códigos de controle (IOCTL)
#define IOCTL_STARTSUSPENDED_BASE 0x800

#define IOCTL_STARTSUSPENDED_GET_PROCESSES CTL_CODE(FILE_DEVICE_UNKNOWN, IOCTL_STARTSUSPENDED_BASE, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_STARTSUSPENDED_RESUME_BY_PID CTL_CODE(FILE_DEVICE_UNKNOWN, IOCTL_STARTSUSPENDED_BASE + 1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_STARTSUSPENDED_RESUME_ALL    CTL_CODE(FILE_DEVICE_UNKNOWN, IOCTL_STARTSUSPENDED_BASE + 2, METHOD_BUFFERED, FILE_ANY_ACCESS)